### ISSUE TITLE
Some sorting parameters cannot be used properly

### ISSUE THREAD

**Issue by ngfchl** [yosemiteyss/qbittorrent_api#23]
**Describe the bug**
Some sorting parameters cannot be used properly. Parameters like "name" and "size" can be used normally, but "TorrentSort" in camel case will report an error. The "sort" in the log is also in camel case instead of underscore: sort=addedOn. 
The official documentation refers to JSON field names.
![image](https://github.com/user-attachments/assets/43ed7951-ec47-4ec4-b894-cd62831742d5)
![image](https://github.com/user-attachments/assets/f7e6c036-af79-40db-9bb7-3913b2a83ebb)

```
flutter: [DIO]<-- END HTTP
flutter: [DIO]--> GET http://192.168.123.5:8997/api/v2/torrents/info?filter=all&sort=addedOn&reverse=false
flutter: [DIO][HEADER] content-type:application/x-www-form-urlencoded
flutter: [DIO][HEADER] cookie:SID=+aqD5QEF3Cag2FKs+DVQNI2aPJpyIXe/
flutter: [DIO]--> END GET
[GETX] CLOSE BOTTOMSHEET 150574250
flutter: [DIO]<-- HTTP FAILED: DioException [bad response]: This exception was thrown because the response has a status code of 400 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 400 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: QBittorrentException: statusCode: 400, statusMessage: Bad Request, message: This exception was thrown because the response has a status code of 400 and RequestOptions.validateStatus was configured to throw for this status code.
The status code of 400 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.

#0      DioClient._exceptionHandler (package:qbittorrent_api/src/network/dio_client.dart:163:7)
<asynchronous suspension>
#1      TorrentsController.getTorrentsList (package:qbittorrent_api/src/v2/torrents/torrents_controller.dart:31:32)
<asynchronous suspension>
#2      TorrentsController.subscribeTorrentsList (package:qbittorrent_api/src/v2/torrents/torrents_controller.dart:45:11)
<asynchronous suspension>
#3      QBittorrentController.subTorrentList.<anonymous closure> (package:harvest/app/q_bittorrent/controller.dart:194:17)
<asynchronous suspension>
```
**Plugin version**
- Version: [1.2.1]

**Screenshots**
<img width="812" alt="image" src="https://github.com/user-attachments/assets/fa6ef9d3-c19d-4cee-8856-74aba8320abc">
<img width="455" alt="image" src="https://github.com/user-attachments/assets/276d24fc-a6c2-4c1f-9524-f5084c20e03d">
<img width="642" alt="image" src="https://github.com/user-attachments/assets/fc1ffd84-82f2-4b52-aae3-d7ebd0dc4d0c">
<img width="701" alt="image" src="https://github.com/user-attachments/assets/81925337-e0e9-4fed-a2ae-3a96890a49bb">

<img width="1614" alt="image" src="https://github.com/user-attachments/assets/e4371b07-00e2-4288-8744-2428724ada5b">

**Comment by yosemiteyss** [comment]
Fixed in 1.2.2
